name: Deploy to EC2

on:
  push:
    branches:
      - dev   # Runs when code is pushed to dev branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}       # EC2 public IP
          username: ${{ secrets.EC2_USER }}   # Usually ec2-user
          key: ${{ secrets.EC2_KEY }}         # Private key stored as secret
          script: |
            cd /var/www/html/GPSCPANEL_PROD
            git pull origin dev
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:clear
            php artisan cache:clear